server:
  port: 8787

jwtAuthConfigs:
  authLoginUrl: /api/authentication
#  // Signing key for HS512 algorithm
  jwtSecret: n2r5u8x/A%D*G-KaPdSgVkYp3s6v9y$B&E(H+MbQeThWmZq4t7w!z%C*F-J@NcRf

logging:
  config: classpath:logback.xml